rootProject.name = "studyjam"
include("core")
include("domain")
include("remoting")
include("report")
include("mail")
include("external-files")
include("meeting")
include("testing")
include("auth")
include("quiz")
include("api-gateway")
include("bot")